-- 初始菜单树（与前端侧栏/顶栏一致，由服务端下发）
-- 仅当 sys_menu 为空时插入，单条语句避免 Spring 按分号分割导致 DO 块解析失败
INSERT INTO sys_menu (id, code, name_key, path, parent_id, sort_order, icon, permission, status, created_at, updated_at)
SELECT v.id, v.code, v.name_key, v.path, v.parent_id, v.sort_order, v.icon, v.permission, v.status, v.created_at, v.updated_at
FROM (VALUES
(1::bigint, 'home', 'menu.home', '/home', NULL::bigint, 1, 'HomeOutlined', 'home:view', 'enabled', now(), now()),
(2::bigint, 'qualityInspection', 'menu.qualityInspection', '/qualityInspection', NULL::bigint, 2, 'CheckCircleOutlined', 'qualityInspection:view', 'enabled', now(), now()),
(21::bigint, 'qualityBusiness', 'menu.quality.business', NULL, 2::bigint, 1, NULL, 'qualityInspection:business:view', 'enabled', now(), now()),
(211::bigint, 'workstationManage', 'menu.quality.workstationManage', '/qualityInspection/workstationManage', 21::bigint, 1, NULL, 'qualityInspection:workstationManage:view', 'enabled', now(), now()),
(212::bigint, 'inspectionBench', 'menu.quality.inspectionBench', '/qualityInspection/inspectionBench', 21::bigint, 2, NULL, 'qualityInspection:inspectionBench:view', 'enabled', now(), now()),
(213::bigint, 'workOrderManage', 'menu.quality.workOrderManage', '/qualityInspection/workOrderManage', 21::bigint, 3, NULL, 'qualityInspection:workOrder:view', 'enabled', now(), now()),
(214::bigint, 'reinspectionRecord', 'menu.quality.reinspectionRecord', '/qualityInspection/reinspectionRecord', 21::bigint, 4, NULL, 'qualityInspection:reinspection:view', 'enabled', now(), now()),
(22::bigint, 'qualityConfig', 'menu.quality.config', NULL, 2::bigint, 2, NULL, 'qualityInspection:config:view', 'enabled', now(), now()),
(221::bigint, 'workshopConfig', 'menu.quality.workshopConfig', '/qualityInspection/config/workshop', 22::bigint, 1, NULL, 'qualityInspection:workshop:view', 'enabled', now(), now()),
(222::bigint, 'areaConfig', 'menu.quality.areaConfig', '/qualityInspection/config/area', 22::bigint, 2, NULL, 'qualityInspection:area:view', 'enabled', now(), now()),
(223::bigint, 'benchConfig', 'menu.quality.benchConfig', '/qualityInspection/config/bench', 22::bigint, 3, NULL, 'qualityInspection:bench:view', 'enabled', now(), now()),
(224::bigint, 'wireHarnessType', 'menu.quality.wireHarnessType', '/qualityInspection/config/wireHarnessType', 22::bigint, 4, NULL, 'qualityInspection:wireHarness:view', 'enabled', now(), now()),
(225::bigint, 'terminalConfig', 'menu.quality.terminalConfig', '/qualityInspection/config/terminal', 22::bigint, 5, NULL, 'qualityInspection:terminal:view', 'enabled', now(), now()),
(23::bigint, 'qualityStatistics', 'menu.quality.statistics', NULL, 2::bigint, 3, NULL, 'qualityInspection:statistics:view', 'enabled', now(), now()),
(231::bigint, 'qualityStats', 'menu.quality.qualityStats', '/qualityInspection/statistics/quality', 23::bigint, 1, NULL, 'qualityInspection:stats:view', 'enabled', now(), now()),
(232::bigint, 'qualityReport', 'menu.quality.qualityReport', '/qualityInspection/statistics/report', 23::bigint, 2, NULL, 'qualityInspection:report:view', 'enabled', now(), now()),
(24::bigint, 'qualityTask', 'menu.quality.task', NULL, 2::bigint, 4, NULL, 'qualityInspection:task:view', 'enabled', now(), now()),
(241::bigint, 'taskTemplate', 'menu.quality.taskTemplate', '/qualityInspection/task/template', 24::bigint, 1, NULL, 'qualityInspection:taskTemplate:view', 'enabled', now(), now()),
(3::bigint, 'deploy', 'menu.deploy', '/deploy', NULL::bigint, 3, 'SettingOutlined', 'deploy:view', 'enabled', now(), now()),
(31::bigint, 'deployTask', 'menu.deploy.task', '/deploy/task', 3::bigint, 1, NULL, 'deploy:task:view', 'enabled', now(), now()),
(32::bigint, 'deployRobot', 'menu.deploy.robot', NULL, 3::bigint, 2, NULL, 'deploy:robot:view', 'enabled', now(), now()),
(321::bigint, 'robotList', 'menu.deploy.robotList', '/deploy/robot/list', 32::bigint, 1, NULL, 'deploy:robotList:view', 'enabled', now(), now()),
(322::bigint, 'robotType', 'menu.deploy.robotType', '/deploy/robot/type', 32::bigint, 2, NULL, 'deploy:robotType:view', 'enabled', now(), now()),
(323::bigint, 'robotParts', 'menu.deploy.robotParts', '/deploy/robot/parts', 32::bigint, 3, NULL, 'deploy:robotParts:view', 'enabled', now(), now()),
(324::bigint, 'robotGroup', 'menu.deploy.robotGroup', '/deploy/robot/group', 32::bigint, 4, NULL, 'deploy:robotGroup:view', 'enabled', now(), now()),
(325::bigint, 'chargeStrategy', 'menu.deploy.chargeStrategy', '/deploy/robot/chargeStrategy', 32::bigint, 5, NULL, 'deploy:chargeStrategy:view', 'enabled', now(), now()),
(326::bigint, 'homingStrategy', 'menu.deploy.homingStrategy', '/deploy/robot/homingStrategy', 32::bigint, 6, NULL, 'deploy:homingStrategy:view', 'enabled', now(), now()),
(327::bigint, 'configTemplate', 'menu.deploy.configTemplate', '/deploy/robot/configTemplate', 32::bigint, 7, NULL, 'deploy:configTemplate:view', 'enabled', now(), now()),
(33::bigint, 'deployScene', 'menu.deploy.scene', NULL, 3::bigint, 3, NULL, 'deploy:scene:view', 'enabled', now(), now()),
(331::bigint, 'mapManage', 'menu.deploy.mapManage', '/deploy/scene/map', 33::bigint, 1, NULL, 'deploy:map:view', 'enabled', now(), now()),
(34::bigint, 'systemSetting', 'menu.deploy.systemSetting', '/deploy/setting', 3::bigint, 4, NULL, 'deploy:setting:view', 'enabled', now(), now()),
(35::bigint, 'deployUser', 'menu.deploy.user', NULL, 3::bigint, 5, NULL, 'deploy:user:view', 'enabled', now(), now()),
(351::bigint, 'userManage', 'menu.deploy.userManage', '/deploy/users', 35::bigint, 1, NULL, 'deploy:user:view', 'enabled', now(), now()),
(352::bigint, 'roleManage', 'menu.deploy.roleManage', '/deploy/roles', 35::bigint, 2, NULL, 'deploy:role:view', 'enabled', now(), now()),
(353::bigint, 'menuManage', 'menu.deploy.menuManage', '/deploy/menus', 35::bigint, 3, NULL, 'deploy:menu:view', 'enabled', now(), now()),
(4::bigint, 'operation', 'menu.operation', '/operation', NULL::bigint, 4, 'ToolOutlined', 'operation:view', 'enabled', now(), now()),
(41::bigint, 'operationMonitor', 'menu.operation.monitor', '/operation/monitoring', 4::bigint, 1, NULL, 'operation:monitor:view', 'enabled', now(), now()),
(42::bigint, 'operationTask', 'menu.operation.task', '/operation/tasks', 4::bigint, 2, NULL, 'operation:task:view', 'enabled', now(), now()),
(43::bigint, 'operationRobot', 'menu.operation.robot', '/operation/robots', 4::bigint, 3, NULL, 'operation:robot:view', 'enabled', now(), now()),
(44::bigint, 'operationNotification', 'menu.operation.notification', NULL, 4::bigint, 4, NULL, 'operation:notification:view', 'enabled', now(), now()),
(441::bigint, 'exceptionNotify', 'menu.operation.exceptionNotify', '/operation/notification/exception', 44::bigint, 1, NULL, 'operation:exception:view', 'enabled', now(), now()),
(442::bigint, 'loginLog', 'menu.operation.loginLog', '/operation/notification/loginLog', 44::bigint, 2, NULL, 'operation:loginLog:view', 'enabled', now(), now()),
(443::bigint, 'operationLog', 'menu.operation.operationLog', '/operation/notification/operationLog', 44::bigint, 3, NULL, 'operation:operationLog:view', 'enabled', now(), now()),
(444::bigint, 'apiLog', 'menu.operation.apiLog', '/operation/notification/apiLog', 44::bigint, 4, NULL, 'operation:apiLog:view', 'enabled', now(), now()),
(45::bigint, 'operationFile', 'menu.operation.file', '/operation/files', 4::bigint, 5, NULL, 'operation:file:view', 'enabled', now(), now()),
(46::bigint, 'operationUpgrade', 'menu.operation.upgrade', NULL, 4::bigint, 6, NULL, 'operation:upgrade:view', 'enabled', now(), now()),
(461::bigint, 'packageManage', 'menu.operation.packageManage', '/operation/upgrade/package', 46::bigint, 1, NULL, 'operation:package:view', 'enabled', now(), now()),
(462::bigint, 'publishManage', 'menu.operation.publishManage', '/operation/upgrade/publish', 46::bigint, 2, NULL, 'operation:publish:view', 'enabled', now(), now()),
(47::bigint, 'operationService', 'menu.operation.service', '/operation/services', 4::bigint, 7, NULL, 'operation:service:view', 'enabled', now(), now()),
(5::bigint, 'dataStatistics', 'menu.dataStatistics', '/dataStatistics', NULL::bigint, 5, 'BarChartOutlined', 'dataStatistics:view', 'enabled', now(), now()),
(51::bigint, 'deviceStatistics', 'menu.dataStatistics.device', '/dataStatistics/device', 5::bigint, 1, NULL, 'dataStatistics:device:view', 'enabled', now(), now()),
(52::bigint, 'exceptionStatistics', 'menu.dataStatistics.exception', '/dataStatistics/exception', 5::bigint, 2, NULL, 'dataStatistics:exception:view', 'enabled', now(), now())
) AS v(id, code, name_key, path, parent_id, sort_order, icon, permission, status, created_at, updated_at)
WHERE NOT EXISTS (SELECT 1 FROM sys_menu LIMIT 1);
-- 校正序列（仅当表为空时上面 INSERT 会执行，此语句可安全重复执行）
SELECT setval('sys_menu_id_seq', (SELECT COALESCE(MAX(id), 1) FROM sys_menu));
